site_name: SmellscaPy
site_url: https://mydomain.org/mysite
copyright: Copyright &copy; 2025 Giulia Torriani & Olga Somova, Eurac Research
site_dir: site


nav:
  - Home: index.md
  - Overview: overview/index.md
  - Quick Start: quick_start/index.md     
  - Tutorials:
    - tutorials/index.md
    - "Loading Smellscape Data": tutorials/loading_smellscape_data.md
    - "Data Validation": tutorials/data_validation_processing.md 
    - "Calculating Circumplex Coordinates": tutorials/calculating_pleasantness_presence_coordinates.md
    - "Visualisations": tutorials/visualizations.md
    - "Full Project Example": tutorials/fullprojectexample.md
  - API Reference:
    - Data Example: reference/DataExample.md
    - Survey: reference/survey.md
    - Calculations: reference/calculations.md
    - Plotting: 
      - Scatter: reference/plotting/scatter.md
      - Density: reference/plotting/density.md
      - Simple density: reference/plotting/simple_density.md
      - Utils: reference/plotting/utils.md
  - Changelog: changelog/index.md
  - Aknowledgments: aknowledgments/index.md


theme:
  name: material
  logo: assets/logo.png
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.expand
    - navigation.path
    - navigation.top
    - content.code.annotate
    - content.code.copy
    - content.action.edit
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

markdown_extensions:
  - toc

plugins: 
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [., "src"]
          options:
            docstring_section_style: spacy
            docstring_style: "numpy"
            separate_signature: true
            merge_init_into_class: true
            show_symbol_type_toc: true
            modernize_annotations: true
            summary: true
          inventories:
            - "https://docs.python.org/3/objects.inv"
  - include-markdown:
      opening_tag: "{!"
      closing_tag: "!}"

